"""add description to project

Revision ID: 6d706726723e
Revises: b75d79e6ee86
Create Date: 2026-01-13 11:28:58.804941

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6d706726723e"
down_revision: Union[str, Sequence[str], None] = "b75d79e6ee86"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects", sa.Column("description", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "description")
    # ### end Alembic commands ###
